// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArwlrqSGMd379_UX0bpN9AxaQ14bYxspQ',
    appId: '1:21422812082:web:2c64d7e42c645053e312ab',
    messagingSenderId: '21422812082',
    projectId: 'deltasend-pbm4',
    authDomain: 'deltasend-pbm4.firebaseapp.com',
    storageBucket: 'deltasend-pbm4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg1-O5FY7-uqjsr-PJND3dt_H5nBG2-nA',
    appId: '1:21422812082:android:c101832119ad3ebbe312ab',
    messagingSenderId: '21422812082',
    projectId: 'deltasend-pbm4',
    storageBucket: 'deltasend-pbm4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXhL--ggeObxsb_NcOMS2hXRibHeJcF5w',
    appId: '1:21422812082:ios:cfd7a52077ad5287e312ab',
    messagingSenderId: '21422812082',
    projectId: 'deltasend-pbm4',
    storageBucket: 'deltasend-pbm4.firebasestorage.app',
    iosBundleId: 'com.example.deltasend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXhL--ggeObxsb_NcOMS2hXRibHeJcF5w',
    appId: '1:21422812082:ios:cfd7a52077ad5287e312ab',
    messagingSenderId: '21422812082',
    projectId: 'deltasend-pbm4',
    storageBucket: 'deltasend-pbm4.firebasestorage.app',
    iosBundleId: 'com.example.deltasend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArwlrqSGMd379_UX0bpN9AxaQ14bYxspQ',
    appId: '1:21422812082:web:b0d1e3d576ed7b2fe312ab',
    messagingSenderId: '21422812082',
    projectId: 'deltasend-pbm4',
    authDomain: 'deltasend-pbm4.firebaseapp.com',
    storageBucket: 'deltasend-pbm4.firebasestorage.app',
  );
}
